# mod/help.py
help_text = (
    "<h2>Help for Aguida Multimodal Analyzer</h2>"
    "<p>Welcome to the Aguida Multimodal Analyzer. This tool is designed to help you analyze and gain insights from diverse multimodal data sources. Below are some instructions to help you get started and make the most of the application's features.</p>"
    "<h3>Getting Started</h3>"
    "<ul>"
    "<li><strong>Importing Data:</strong> To import data, navigate to the 'File' menu and select 'Import'. Choose the data files you wish to analyze (e.g., heart rate, gaze tracking, facial analysis).</li>"
    "<li><strong>Setting Up Devices:</strong> Ensure all devices (heart rate monitors, eye trackers, cameras) are properly set up and calibrated before starting data collection.</li>"
    "</ul>"
    "<h3>Using the Application</h3>"
    "<ul>"
    "<li><strong>Analyzing Data:</strong> Once data is imported, use the 'Analyze' menu to select the type of analysis you wish to perform. Options include statistical analysis, data visualization, and feature extraction.</li>"
    "<li><strong>Viewing Results:</strong> Analysis results are displayed in the main window. You can switch between different views (e.g., graphs, charts, tables) using the tabs.</li>"
    "</ul>"
    "<h3>Troubleshooting</h3>"
    "<ul>"
    "<li><strong>Data Import Issues:</strong> If you encounter issues while importing data, ensure the files are in the correct format and not corrupted. Refer to the user manual for supported file types.</li>"
    "<li><strong>Device Calibration:</strong> Improperly calibrated devices may result in inaccurate data. Follow the calibration instructions provided with your devices.</li>"
    "</ul>"
    "<h3>Further Resources</h3>"
    "<ul>"
    "<li>For more detailed instructions, visit our <a href='http://example.com/user-manual'>User Manual</a>.</li>"
    "<li>If you need additional support, contact our support team at <a href='mailto:support@example.com'>support@example.com</a>.</li>"
    "</ul>"
)
